[versions]
gradle = "8.13.2"
kotlin = "2.3.0"
googleServices = "4.4.4"
crashlytics = "3.0.6"
kotlinCoroutines = "1.10.2"
ktor = "3.3.3"
kotlinxSerialization = "1.9.0"
koin = "4.1.1"
sqlDelight = "1.5.5"
publisher = "3.13.0"
appCompact = "1.7.1"
coreKtx = "1.17.0"
coil = "3.3.0"
desugar = "2.1.5"
mokkery = "3.1.1"
composeBom = "2025.12.01"
activityCompose = "1.12.2"
navigationCompose = "2.9.1"
dataStorePreferences = "1.2.0"
lifecycle = "2.10.0"
kotlinxDateTime = "0.7.1"
leakcanary = "2.14"
firebase = "34.7.0"
kaspresso = "1.6.0"
collectionsImmutable = "0.4.0"
ktLint = "13.1.0"
tripletPlay = "3.13.0"
compose = "1.11.0-alpha01"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompact" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.9.6" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
koin-compose-viewmodel-navigation = { group = "io.insert-koin", name = "koin-compose-viewmodel-navigation", version.ref = "koin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "collectionsImmutable" }
kaspresso = { module = "com.kaspersky.android-components:kaspresso", version.ref = "kaspresso" }
kaspresso-allure-support = { module = "com.kaspersky.android-components:kaspresso-allure-support", version.ref = "kaspresso" }
kaspresso-compose-support = { module = "com.kaspersky.android-components:kaspresso-compose-support", version.ref = "kaspresso" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
foundation = { module = "androidx.compose.foundation:foundation" }
foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
ui = { module = "androidx.compose.ui:ui" }
material3 = { module = "androidx.compose.material3:material3" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
ui-animation = { module = "androidx.compose.animation:animation-graphics" }
androidx-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

sqlDelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }
sqlDelight-coroutines-extensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqlDelight" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStorePreferences" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }

ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }

ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

#classpath
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }
sqlDelight-gradle-plugin = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqlDelight" }
play-publisher = { module = "com.github.triplet.gradle:play-publisher", version.ref = "publisher" }

[plugins]

application = { id = "com.android.application", version.ref = "gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
google-service = { id = "com.google.gms.google-services", version.ref = "googleServices" }
triplet-play = { id = "com.github.triplet.play", version.ref = "tripletPlay" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
ktLint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktLint" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
cocoa = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqlDelight" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "gradle" }

# Plugins defined by this project
client-compose-multiplatform-feature = { id = "com.bunbeauty.compose.multiplatform.feature", version = "1.0" }
client-android-application = { id = "com.bunbeauty.android.application", version = "1.0" }

[bundles]
navigation = [
    "androidx-navigation-compose",
]
lifecycle = [
    "lifecycle-viewmodel-compose",
]

di = [
    "koin-core",
    "koin-compose",
    "koin-compose-viewmodel",
    "koin-compose-viewmodel-navigation",
]

di-android = [
    "koin-core",
    "koin-android"
]

coil = [
    "coil-network-ktor",
    "coil-compose"
]

kaspresso = [
    "kaspresso",
    "kaspresso-allure-support",
    "kaspresso-compose-support",
]

firebase = [
    "firebase-bom",
    "firebase-crashlytics",
    "firebase-analytics",
    "firebase-messaging",
]

compose = [
    "foundation",
    "foundation-layout",
    "ui",
    "material3",
    "ui-tooling",
    "ui-tooling-preview",
    "ui-viewbinding",
    "ui-animation",
]

ktor = [
    "ktor-client-websockets",
    "ktor-client-content-negotiation",
    "ktor-client-json",
    "ktor-serialization-kotlinx-json",
    "ktor-client-serialization",
    "ktor-client-logging",
    "ktor-client-auth",
]